AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambdas

  Sample SAM Template for lambdas

Parameters:
  UserQueueName:
    Type: String
    Default: users

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Environment:
      Variables:
        USER_QUEUE_URL: !Ref UserQueue

Resources:
  UserQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref UserQueueName

  HttpApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      # Cors:
      #   AllowHeaders: '*'
      #   AllowMethods: '*'
      #   AllowOrigin: '*'

  UserServiceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: users/userService.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !Ref UserQueueName
        - SQSPollerPolicy:
            QueueName: !Ref UserQueueName
      Events:
        UserEvents:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users
            Method: ANY
            RestApiId: !Ref HttpApiGateway
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: 'es2020'
        Sourcemap: true
        EntryPoints:
          - users/userService.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UserServiceApi:
    Description: 'API Gateway endpoint URL for Prod stage for User Name function'
    Value: !Ref HttpApiGateway
  UserServiceFunction:
    Description: 'User Service Function'
    Value: !GetAtt UserServiceFunction.Arn
  UserServiceFunctionIamRole:
    Description: 'Implicit IAM Role created for User Service function'
    Value: !GetAtt UserServiceFunctionRole.Arn
  UserQueue:
    Description: 'User SQS QueueUrl'
    Value: !Ref UserQueue
